project:
  type: website
  output-dir: docs

website:
  title: "kaylafinley"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - relevant_experience.qmd
      - future_goals.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

